### PR TITLE
local json

### PR DESCRIPTION
**Pull request by gidden**
this is the website PR in a trio of dbtypes-related PRs. It removes `dbtypes.js` from the website, noting its canonical location in the cyclus repo.

### CODE REVIEW

**Comment by gidden** [comment]
note that this is dependent on cyclus/cyclus#1184 and can supercede #157

**Comment by gidden** [comment]
@rwcarlsen, this is also good to go. The website depends on the local dbtypes.js, and the pivot table reads all rows/columns, but by default shows only the c++ type with hdf5/sqlite availability.

**Comment by rwcarlsen** [comment]
Something like this should do it (untested):

```diff
diff --git a/source/arche/dbtypes.rst b/source/arche/dbtypes.rst
index c534bc8..499a6c2 100644
--- a/source/arche/dbtypes.rst
+++ b/source/arche/dbtypes.rst
@@ -49,6 +49,11 @@
     <script type="text/javascript" src="dbtypes.js"></script>
     
     <script type="text/javascript">
+    var dbdata = []
+    $.getJSON("/arche/dbtypes.json", function(json) {
+        dbdata = json;
+    });
+
     function setupPivot(input){
       input.callbacks = {afterUpdateResults: function(){
         $('#results > table').dataTable({
```

**Comment by gidden** [comment]
Yeah, I had something very similar to that which didn't work. We can test
in the morning.

On Mon, Aug 3, 2015 at 9:18 PM, Robert Carlsen <notifications@github.com>
wrote:

> Something like this should do it (untested):
>
> diff --git a/source/arche/dbtypes.rst b/source/arche/dbtypes.rst
> index c534bc8..499a6c2 100644--- a/source/arche/dbtypes.rst+++ b/source/arche/dbtypes.rst@@ -49,6 +49,11 @@
>      <script type="text/javascript" src="dbtypes.js"></script>
>
>      <script type="text/javascript">+    var dbdata = []+    $.getJSON("/arche/dbtypes.json", function(json) {+        dbdata = json;+    });+
>      function setupPivot(input){
>        input.callbacks = {afterUpdateResults: function(){
>          $('#results > table').dataTable({
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus.github.com/pull/162#issuecomment-127456902>
> .
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
ok, ready to go

**Comment by gidden** [comment]
rebased, still ready to go

**Comment by rwcarlsen** [comment]
The dbtypes pivot table is broken when I build the site inside docker - I think this might be because we put the apt version of cloud-sptheme in the website deps image.  I'll be busy with parents most of today, can @gidden verify this problem and possible see if we can get the pip version to work?  Or I can take a look tomorrow.

**Comment by gidden** [comment]
error confirmed

**Comment by gidden** [comment]
separate question: why does the source branch currently work? the cyclus image should not be installing `dbtypes.js`.

**Comment by gidden** [comment]
So, if you remember from previous trials, we have to apt-get cloud:
```
copying static files... 
Exception occurred:
  File "<template>", line 136, in template
ZeroDivisionError: float division by zero
The full traceback has been saved in /tmp/sphinx-err-7_3o5axn.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
make: *** [gh-preview] Error 1
make: *** [html-docker] Error 2
```

**Comment by gidden** [comment]
ok, so in the end I can replicate the error. Using debugging tools, I see that, as expected, the dbtypes.json file is correctly GET'd. I agree that this has something to do with python3 tools. I don't have more time to work on this today. Perhaps @scopatz has some battle stories for using cloud with python 3...

**Comment by scopatz** [comment]
I don't quite understand what you are asking.

**Comment by gidden** [comment]
This PR correctly builds pivot table locally using python2 flavors of cloud and sphinx. It fails to build the table using python3 flavors of the same package. The file is found, thus it is likely some issue with python3 + jQuery + cloud + ...

**Comment by scopatz** [comment]
Hmmm the pivot table is built in pure JS. If this is a python issue, it is in the way the file is being formed.  The docs are copying the json file over to their static dir and installing it?

**Comment by gidden** [comment]
It's doing the exact same thing as with the `dbtypes.js` file and reading
it:
https://github.com/cyclus/cyclus.github.com/pull/162/files#diff-f8ed1024fc7a80f548f9a96ab4ccc149R53

On Thu, Aug 6, 2015 at 10:44 AM, Anthony Scopatz <notifications@github.com>
wrote:

> Hmmm the pivot table is built in pure JS. If this is a python issue, it is
> in the way the file is being formed. The docs are copying the json file
> over to their static dir and installing it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus.github.com/pull/162#issuecomment-128414933>
> .
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by scopatz** [comment]
Ahh, if you are trying to look at the generated site locally (file://) many browsers will prevent you from loading local files as a security measure.  Chrome in particular is very strict about this, though there is a CLI to disable it and allow such files to be loaded.  It is probably easiest to look at this via a web server on localhost.  You can spin one up super quickly in the directory of choice with 

```console
$ python -m SimpleHTTPServer #py2k
$ python -m http.server  # py3k
```

This allows loading of external files.

**Comment by gidden** [comment]
I am currently spinning up a local file server, still have the error.

On Thu, Aug 6, 2015 at 10:58 AM, Anthony Scopatz <notifications@github.com>
wrote:

> Ahh, if you are trying to look at the generated site locally (file://)
> many browsers will prevent you from loading local files as a security
> measure. Chrome in particular is very strict about this, though there is a
> CLI to disable it and allow such files to be loaded. It is probably easiest
> to look at this via a web server on localhost. You can spin one up super
> quickly in the directory of choice with
>
> $ python -m SimpleHTTPServer #py2k
> $ python -m http.server  # py3k
>
> This allows loading of external files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus.github.com/pull/162#issuecomment-128418022>
> .
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
Same issue on chrome and firefox FWIW

On Thu, Aug 6, 2015 at 11:03 AM, Matthew Gidden <gidden@wisc.edu> wrote:

> I am currently spinning up a local file server, still have the error.
>
> On Thu, Aug 6, 2015 at 10:58 AM, Anthony Scopatz <notifications@github.com
> > wrote:
>
>> Ahh, if you are trying to look at the generated site locally (file://)
>> many browsers will prevent you from loading local files as a security
>> measure. Chrome in particular is very strict about this, though there is a
>> CLI to disable it and allow such files to be loaded. It is probably easiest
>> to look at this via a web server on localhost. You can spin one up super
>> quickly in the directory of choice with
>>
>> $ python -m SimpleHTTPServer #py2k
>> $ python -m http.server  # py3k
>>
>> This allows loading of external files.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cyclus/cyclus.github.com/pull/162#issuecomment-128418022>
>> .
>>
>
>
>
> --
> Matthew Gidden, Ph.D.
> Postdoctoral Associate, Nuclear Engineering
> The University of Wisconsin -- Madison
> Ph. 225.892.3192
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by rwcarlsen** [comment]
The cloud sptheme uses jinja templating.  In the newest pip3 version of the
theme, there is content in one of the theme's templates that causes a
zerodivisionerror exception in jinja.  If we use the apt-get version of the
theme, then the template error doesn't occur, but the dbtypes pivot table
doesn't work.  A rock and a hard place.

**Comment by rwcarlsen** [comment]
I found the error.  cloud_sptheme recently (last few weeks) released a new version (1.7) that is broken for us.  I pushed up a fix to the dockerfile that explicitly installs sptheme version 1.6.  Problem solved (in a slightly  unsatisfying way).  @gidden could you rebase this one final time?

**Comment by gidden** [comment]
I'll put it on my list for today.

On Mon, Aug 10, 2015 at 12:08 PM, Robert Carlsen <notifications@github.com>
wrote:

> I found the error. cloud_sptheme recently (last few weeks) released a new
> version (1.7) that is broken for us. I pushed up a fix to the dockerfile
> that explicitly installs sptheme version 1.6. Problem solved (in a slightly
> unsatisfying way). @gidden <https://github.com/gidden> could you rebase
> this one final time?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus.github.com/pull/162#issuecomment-129528487>
> .
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
I'm experiencing sporadic failure on refresh

On Mon, Aug 10, 2015 at 12:12 PM, Matthew Gidden <gidden@wisc.edu> wrote:

> I'll put it on my list for today.
>
> On Mon, Aug 10, 2015 at 12:08 PM, Robert Carlsen <notifications@github.com
> > wrote:
>
>> I found the error. cloud_sptheme recently (last few weeks) released a new
>> version (1.7) that is broken for us. I pushed up a fix to the dockerfile
>> that explicitly installs sptheme version 1.6. Problem solved (in a slightly
>> unsatisfying way). @gidden <https://github.com/gidden> could you rebase
>> this one final time?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cyclus/cyclus.github.com/pull/162#issuecomment-129528487>
>> .
>>
>
>
>
> --
> Matthew Gidden, Ph.D.
> Postdoctoral Associate, Nuclear Engineering
> The University of Wisconsin -- Madison
> Ph. 225.892.3192
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by gidden** [comment]
k fixed

**Comment by scopatz** [comment]
You should report the error upstream, if you haven't already.  The cloud people have fixed issues that I've reported before.

**Comment by rwcarlsen** [comment]
The bug seems to have been fixed in newer versions of the theme.  This was rebased and merged as 0d1323d.  Thanks @gidden!

**Pull request closed without merging**
