### PR TITLE
added cymetric to docs

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by opotowsky** [comment]
@rwcarlsen How do these changes compare to everything you did in cyclusagent.py https://github.com/cyclus/cyclus.github.com/pull/128 (@scopatz may want to have a look too)? I don't want to merge this in without comparing them first.

**Comment by opotowsky** [comment]
@scopatz, @gidden merged in a fix for cyclusagent.py so now there are merge conflicts in that file. I can't get to it today; care to have a look?

**Comment by scopatz** [comment]
Conflicts should now be resolved.

**Comment by opotowsky** [comment]
I noticed the metrics documentation isn't rendering properly. I'm assuming it is a problem within cymetric and not this. Can you confirm this for me before I merge, please?

Thanks, @scopatz!

**Comment by scopatz** [comment]
Seems fine to me.

metrics

**Comment by opotowsky** [comment]
So the doc strings aren't supposed to be shown here? I assumed that would be the case

**Comment by scopatz** [comment]
I think that this might be a bug in the metrics decorator and/or nose.  But shouldn't prevent the merge.

**Comment by gonuke** [comment]
or a bug in sphinx/autodoc's handling of docstrings for decorated functions?

**Comment by scopatz** [comment]
err sorry I meant sphinx not nose.

**Comment by gidden** [comment]
this adds cymetric as a dependency, so that should probably be reflected in the readme

**Comment by scopatz** [comment]
readme updates.

**Comment by opotowsky** [comment]
@scopatz @gonuke @gidden @mbmcgarry @rwcarlsen I'd like more opinions on if I should merge this now or put in a fix to cymetric first. (I have no clue how long that will take me to put in a fix)

**Comment by scopatz** [comment]
@opotowsky I don't think this is worth worrying about in the short term

**Comment by opotowsky** [comment]
Do you mean:
1. this should go in as is to allow the release of cymetric?
or
2. that the documentation isn't necessary?

**Comment by scopatz** [comment]
(1) This should go in as is.

**Comment by gonuke** [comment]
I'm pretty sure the answer is the former (1.) - go in as is.

**Comment by opotowsky** [comment]
Thanks! 

And thanks to @scopatz for the work.

**Pull request merged**
