### PR TITLE
some newsletter update

### PR DESCRIPTION
**Pull request by bam241**
adding links, 
and some publications..

@FlanFlanagan shall we not shape the publications as references ? (it will take less place...)

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
We can do that! Yes!

**Comment by bam241** [comment]
better @FlanFlanagan 

I found 2 refs for you guys @ global 2017, I put both of them, but I am not sure yours is cyclus related...

**Comment by FlanFlanagan** [comment]
I'm not sure the XSgen paper belongs, although I guess it references Cyclus? 

The main focus of the paper is actual the methods used in XSgen.

**Comment by FlanFlanagan** [comment]
But the rest look good!

**Pull request merged**
