### PR TITLE
change instances of master branch to main

### PR DESCRIPTION
**Pull request by abachma2**
This PR changes the instances of `master` branch to `main` branch, now that we have changed the default branch for Cyclus, Cycamore, and Cymetric. This addresses one of the item in #337

### CODE REVIEW

**Review by nsryan2 — APPROVED** [review]
LGTM, all the links altered in this way are either for cyclus or numpy (which has updated their branch from master to main as well)!

**Comment by gonuke** [comment]
Have we actually updated the default branch of this repo yet, though?

**Comment by abachma2** [comment]
We have not done it for this repo, but we did do it for each of the others. We should probably hold off on merging this until we change the default for this repo.

**Comment by gonuke** [comment]
This may need a rebase for a few changes I made in the `Makefile` in #345

**Comment by abachma2** [comment]
Better?

**Review by gonuke — APPROVED** [review]
LGTM - thanks @abachma2

**Pull request merged**
