### PR TITLE
Pyagent Documentation

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by scopatz** [comment]
cc @FlanFlanagan @bam241 @hodger

**Comment by scopatz** [comment]
ping!

**Comment by scopatz** [comment]
Again, if there are no objections, let's merge this!

**Comment by bam241** [comment]
@scopatz sorry I have been busy.
You will have a merge or my comment within an hour!

**Comment by scopatz** [comment]
Thanks!

**Comment by scopatz** [comment]
Thanks @bam241!

**Comment by bam241** [comment]
and it should be online :)

**Comment by scopatz** [comment]
So it is!

**Pull request merged**
