### PR TITLE
fixes and support for recursive alias and containers

### PR DESCRIPTION
**Pull request by rwcarlsen**
Note that this shouldn't be merged until after Reactor, FuelFab, Separations, Enrichment archetypes are merged in.

* Fix side bar links to be local to website so they work correctly in preview modes.

* Fixed cyclusagent directive to handle alias properly and also the deal with the new recursive alias
specification.  Now support recursive container types correctly. Support for
'internal' state var annotation that indicates a var is not for user
consumption. Fixed a couple other bugs.

* adjustements to show new cycamore archetype docs in user guide

### CODE REVIEW

**Comment by rwcarlsen** [comment]
ping - this should be good for a merge now.  It will be exciting to see the new facilities with their docs on the website :-)

**Comment by mbmcgarry** [comment]
I can look at this on Thursday if no one gets to it sooner.


Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------
From: Robert Carlsen
Date:04/27/2015 2:31 PM (GMT-06:00)
To: "cyclus/cyclus.github.com"
Subject: Re: [cyclus.github.com] fixes and support for recursive alias and containers (#128)


ping - this should be good for a merge now. It will be exciting to see the new facilities with their docs on the website :-)

-

**Comment by mbmcgarry** [comment]
I get an error building the webpage:
```
Exception occurred:
  File "/Users/mbmcgarry/git/cyclus.github.com/source/cyclusagent.py", line 110, in load_annotations
    "{0}.".format(self.agentspec))
ValueError: Error reading agent annotations for :cycamore:Enrichment.
The full traceback has been saved in /var/folders/lt/0ndrtcb92n1glvyr52yl61tw0000gn/T/sphinx-err-xnKE4p.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```

**Comment by gidden** [comment]
What do you get when you run `cyclus --agent-annotations
:cycamore:Enrichment`?

On Thu, Apr 30, 2015 at 10:39 AM, mbmcgarry <notifications@github.com>
wrote:

> I get an error building the webpage:
>
> Exception occurred:
>   File "/Users/mbmcgarry/git/cyclus.github.com/source/cyclusagent.py", line 110, in load_annotations
>     "{0}.".format(self.agentspec))
> ValueError: Error reading agent annotations for :cycamore:Enrichment.
> The full traceback has been saved in /var/folders/lt/0ndrtcb92n1glvyr52yl61tw0000gn/T/sphinx-err-xnKE4p.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cyclus.github.com/pull/128#issuecomment-97843409>
> .
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by mbmcgarry** [comment]
Cancel that - I was on an old cycamore branch.

**Comment by mbmcgarry** [comment]
It looks like the sidebar links now do not work at all rather than the previous functionality of pointing to the external website.

**Comment by gidden** [comment]
@rwcarlsen, I am seeing the same thing @mbmcgarry sees. Can you revert your changes to the layout please.

**Comment by gidden** [comment]
I'll commit a fix since this is blocking release work

**Comment by gidden** [comment]
merged with a rebase

**Pull request closed without merging**
