### PR TITLE
Pphw dox rev2

### PR DESCRIPTION
**Pull request by gonuke**
This depends on cyclus PR https://github.com/cyclus/cyclus/pull/1301 and cycamore PR https://github.com/cyclus/cycamore/pull/433

### CODE REVIEW

**Comment by scopatz** [comment]
LGTM, but what do you mean by "coordinated?"

**Comment by gonuke** [comment]
By "coordinated with", I meant "depends on".    Testing requires setting  `GIT_FORK=gonuke` `GIT_BRANCH=pphw_dox_rev2` until those PR's are merged.

**Comment by scopatz** [comment]
So should they just be merged at the same time?  If that is all it is, I can merge them now.

**Comment by gonuke** [comment]
Yes, the Cyclus and Cycamore PRs are independent, but the fuelcycle.org PR depends on the others, so merge in that order.

**Comment by scopatz** [comment]
Thanks @gonuke!

**Pull request merged**
