### PR TITLE
Fix some items to build website

### PR DESCRIPTION
**Pull request by abachma2**
The website wasn't building correctly because of the new `cyclus::toolkit::TotalInvTracker` added into Cyclus. I have added it to a list of res bufs to skip over when building some of the agent documentation. I have also made other miscellaneous changes to remove some of the warning messages (like a linked file doesn't exist) so that broken links aren't as much of an issue. 

In `source/cyclusagents.py` I also removed some package imports that aren't used anywhere. This is especially important because one of those imports is deprecated and will be removed in the next minor version of the package.

### CODE REVIEW

**Review by bennibbelink — COMMENTED** [review]
Thanks for getting this working @abachma2!  I'm not super familiar with the website building process but these changes look fairly straightforward.  I'll defer to someone more familiar to officially approve the PR.

Something else to consider - I built the website locally and saw a lot of errors/warnings from Sphinx.  Most of them can probably be ignored but I noticed this particular block of warnings:
Screenshot 2024-02-14 at 8 37 55 PM

When I checked the page the images were in fact not loaded since they don't exist.
Screenshot 2024-02-14 at 8 38 29 PM

This is just one issue I noticed... it may be worth looking a little closer at the Sphinx logs to find other issues

**Comment by abachma2** [comment]
Those errors are related to an issue I made today (#330) if you want to take a look at it.

**Review by gonuke — APPROVED** [review]
Thanks for this cleanup @abachma2

**Comment by nuclearkatie** [comment]
Thanks @abachma2! I haven't worked on the website before so I didn't even think to check if `TotalInvTracker` would affect this repo, appreciate you getting that addressed quickly

**Pull request merged**
