### PR TITLE
CEP1 modification: lazy consensus for languishing CEPs

### PR DESCRIPTION
**Pull request by scopatz**
This was discussed and approved back at the Community meeting in July, but please feel free to comment

### CODE REVIEW

**Comment by FlanFlanagan** [comment]
I'm okay with this change.

**Comment by scopatz** [comment]
It seems like this has enough approval.  Would someone please merge? Thanks! :)

**Comment by bam241** [comment]
merged and published.

**Comment by scopatz** [comment]
Woohoo progress!

**Pull request merged**
