### PR TITLE
micro version number modification to cep3

### PR DESCRIPTION
**Pull request by scopatz**
A few lines that will make development easier going forward.

### CODE REVIEW

**Comment by gonuke** [comment]
I support this change in practice, but recommend that we also add indications about this version naming policy to other places on the website for the benefit of users.

**Comment by scopatz** [comment]
Thanks @gonuke - I have added some warnings around the site to this effect.

**Comment by katyhuff** [comment]
:+1:

**Comment by bam241** [comment]
thx @scopatz

**Pull request merged**
