### PR TITLE
Update publications

### PR DESCRIPTION
**Pull request by abachma2**
This PR addresses #371, by adding the v1.6 citations and adding some newer publications. In #371 I asked about the ordering of the publications, but it's not clear to me how the literature and presentation sections get ordered, as it isn't the order of the bib file.

### CODE REVIEW

**Comment by bennibbelink** [comment]
Build is failing due to some of the new packaging features: 

```Exception occurred:
  File "/cyclus.github.com/source/cyclusagent.py", line 164, in _type
    raise TypeError(msg.format(given))
TypeError: Note that 'package' is not a valid XML schema data type, see http://www.w3.org/TR/xmlschema-2/ for more information.
```


Looks like there are a few sets of hardcoded types in `cyclusagent.py` (lines 104-153), @nuclearkatie do you know what specifically needs to be added to that script to accommodate your recent work?

**Comment by nuclearkatie** [comment]
Yeah I raised this in #373. I was gonna fix it in conjunction with some other packaging documentation but I'll put in a quick fix just for this now that other people are looking to push updates to the website

**Comment by bennibbelink** [comment]
#373 has been addressed by #375.  With a rebase this should be ready to review @abachma2

**Comment by abachma2** [comment]
Thanks @bennibbelink  and @nuclearkatie. Tests are passing now and this should be good for someone to review.

**Comment by bennibbelink** [comment]
The commit I just made should make it so that the publications are listed in the order the appear in `pubs.bib`.  You can manually reorder them in that file to your liking (reverse chronological seems fine to me).  This worked for me locally, let me know if you run into issues

There is a way to write our own custom style/sorting in Sphinx but that feels like overkill for the number of publications we list

**Comment by abachma2** [comment]
Thanks for adding that in @bennibbelink. I've reordered the bib files to be in reverse order. We still need a review on this PR

**Review by nuclearkatie — APPROVED** [review]
LGTM! Thanks @abachma2 for updating this

**Pull request merged**
