### PR TITLE
Post tutorial website changes

### PR DESCRIPTION
**Pull request by gonuke**
A number of changes starting with moving the tutorials.

### CODE REVIEW

**Comment by mbmcgarry** [comment]
thanks @gonuke !

**Comment by mbmcgarry** [comment]
I have encountered errors when trying to gh-publish (as in the past).  Perhaps someone else can publish this?

**Comment by rwcarlsen** [comment]
Sounds like we need a dockerfile to build the website!

**Comment by gidden** [comment]
see #168

**Pull request merged**
