### PR TITLE
update README

### PR DESCRIPTION
**Pull request by bam241**
Update sphinx requirement in readme

### CODE REVIEW

**Comment by scopatz** [comment]
I don't think this is the correct thing to do.  It is better to fix the bug than document allowable versions.

**Comment by scopatz** [comment]
Thanks for putting this in though!

**Comment by gonuke** [comment]
Is this still relevant?

**Comment by scopatz** [comment]
I think not.  I think there was one version that was broken and then more recent versions of sphixed have fixed it.

**Comment by bam241** [comment]
right closing!

**Pull request closed without merging**
