### PR TITLE
fix tab and incorrect python3 string handling

### PR DESCRIPTION
**Pull request by rwcarlsen**
The website build was broken by some additions for json snippet generation/printing in #186.  This should fix those issues.

### CODE REVIEW

**Comment by rwcarlsen** [comment]
@scopatz - will this change break python2 - I tried to do a preliminary check that seemed fine, but perhaps a full python2 system would provide more assurance.

**Comment by Baaaaam** [comment]
@rwcarlsen I confirme this is working using:
Python 3.5.1
Sphinx v1.4
Cloud Version: 1.7.1

don't know if we want to wait python2 compatibility validation....

**Comment by Baaaaam** [comment]
working with : 
Python 2.7.10
Sphinx v1.4
Cloud Version: 1.7.1

merging

**Comment by scopatz** [comment]
Yeah, I couldn't see a way this would break things @rwcarlsen

**Pull request merged**
