### PR TITLE
Py API docs

### PR DESCRIPTION
**Pull request by scopatz**
CC @Baaaaam @FlanFlanagan

### CODE REVIEW

**Comment by Baaaaam** [comment]
@scopatz I just see this PR, I'll check this asap!

**Comment by scopatz** [comment]
Ping @bam241 @FlanFlanagan

**Comment by scopatz** [comment]
ping again!

**Comment by bam241** [comment]
I run on some error when trying to build locally the website:
```
/Users/mouginot/work/website/cyclus.github.com/source/python/events.rst:7: WARNING: autodoc: failed to import module 'cyclus.event'; the following exception was raised:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
ImportError: No module named 'cyclus.event'
```

```
/Users/mouginot/work/website/cyclus.github.com/source/user/cymetric/api/cyclus.rst:7: WARNING: autodoc: failed to import module 'cymetric.cyclus'; the following exception was raised:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
ImportError: No module named 'cymetric.cyclus'
/Users/mouginot/work/website/cyclus.github.com/source/user/cymetric/api/typesystem.rst:7: WARNING: autodoc: failed to import module 'cymetric.typesystem'; the following exception was raised:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
ImportError: No module named 'cymetric.typesystem'
```

**Comment by bam241** [comment]
I have did have cyclus /develop uptodate and compuled on my computer

**Comment by bam241** [comment]
those error have already been reported (by me) sorry

**Comment by bam241** [comment]
@scopatz the `Cyclus Type System (cyclus.typesystem)` link send me to an empty page as well as the `Event Loop (cyclus.events)` one.

Otherwise looks good. if it is normal, I'll be happy to merge your changes.

**Comment by scopatz** [comment]
Ok @bam241 - thanks for point that out. I noticed a few other warnings and fixed them up too while I was at it. This should be ready for another look.

**Comment by bam241** [comment]
I don't have the warning/error any more, but the `cyclus.event` page is still empty ? is it normal ?

**Comment by scopatz** [comment]
Yes, because the pages is for cyclus.events, not cyclus.event

**Comment by bam241** [comment]
Oh sorry my mistake: `Cyclus Type System (cyclus.typesystem)` is empty not the `cyclus.events` one

**Comment by scopatz** [comment]
Oh that is probably because typesystem doesn't contain anything with docstrings on develop. I wouldn't worry about this until after pyagent is merged.

**Comment by bam241** [comment]
it's published!

**Comment by scopatz** [comment]
Thanks!

**Pull request merged**
